### ISSUE TITLE
Incorrect API token breaks homebridge

### ISSUE THREAD

**Issue by ShubhChopra** [Teslemetry/homebridge#10]
**Describe The Issue:**
1) If the API token is incorrect it causes home bridge to restart again and again with out any description so the rest of the plugin fail.
2) In sufficient documentation on which API token is required basically to subscribe to tessie/Teslemetry then generate API token then add that token to plugin.

**To Reproduce:**
just add an incorrect API token.

**Expected behavior:**
clear logs + a reset threshold.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:

**Comment by Bre77** [comment]
This has been addressed in the next release. It now logs an error rather than crashing.
