### ISSUE TITLE
option to select which vehicles are displayed in homebridge

### ISSUE THREAD

**Issue by abonstu** [Teslemetry/homebridge#11]
**Describe the solution you'd like:**
configuration option to constrain which vehicles are reflected in homebridge, for example:
- an option to include only vehicles which you are OWNER
- whitelist of vehicles that should be reflected in homebridge

scenario: i have OWNER access to my tesla model 3, and DRIVER access to my dads model Y; i dont want to see my dads car (who lives elsewhere) in my homebridge

**Comment by Bre77** [comment]
This has been added to version 0.4.0. You can configure the VIN of vehicles you want to ignore.

**Comment by abonstu** [comment]
faster than a fat kid on a snickers bar 👍

**Comment by Bre77** [comment]
> faster than a fat kid on a snickers bar 👍 

I either do it immediately, or forget this ever existed.
