### ISSUE TITLE
Reduced logs

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Teslemetry/homebridge#2]
**Is your feature request related to a problem? Please describe:**

I suggest writing only successful and failed actions to user logs even in beta trials. Provide a check box for verbose logs in the configuration gui. The current logs completely fill my Homebridge’s log buffer for view from the log viewer. 

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Bre77** [comment]
Is your Homebridge in debug mode? I only have very verbose logging in debug mode, but I am making changes to remove anything from log to debug that isnt important to the user.

**Comment by TeslaOwnerTips** [comment]
{
    "bridge": {
        "name": "Dummy Devices 494-00-494",
        "username": "0E:3A:A5:DD:6C:3E",
        "port": 51946,
        "pin": "494-00-494"
    },
    "accessories": [
        {
            "name": "Washroom Fan 20 Minutes ",
            "interval": 12000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "Washroom Fan 40 Minutes ",
            "interval": 24000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "Washroom Fan 60 Minutes",
            "interval": 36000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "Automation Every 5 Minutes ",
            "interval": 3000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "Automation Every Hour",
            "interval": 30000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "LR Occupancy 5 Minutes ",
            "interval": 3000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "WR Light 100 Minutes",
            "interval": 60000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "BkYrd Light 200 Minutes ",
            "interval": 120000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "Patio Light 400 Minutes ",
            "interval": 240000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "HT Lights 400 Minutes ",
            "interval": 240000,
            "accessory": "EggTimerBulb"
        },
        {
            "name": "GL open",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "GL close",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "GR open",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "GR close",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FHF fix hanger fan",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FOF",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FBF",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FB return air",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "FLF",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FKF",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 1000000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Tb",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Hb",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Wb",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Wo",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FLo",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FLb",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FLp",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "FLof",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "HVAC Bedroom",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "HVAC Office",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "HVAC Hanger",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "HVAC Living",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Thermostat Cool Overnight ",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Thermostat 1C Up",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Thermostat 1C Down",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "House 1C Up",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "House 1C Down",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "18 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "19 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "20 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "21 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "22 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "23 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "24 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "25 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "26 C",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Thermostat Mode Off",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Thermostat Mode Cool",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Thermostat Mode Heat",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Cooling Overnight ",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 100,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Restart Bond Fans",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Restart Smart Life Outlets",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": true,
            "accessory": "DummySwitch"
        },
        {
            "name": "Turn Off On Front Door Camera ",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 5000,
            "random": false,
            "resettable": true,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Laundry Open",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 200,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Laundry Close",
            "stateful": false,
            "dimmer": false,
            "reverse": false,
            "time": 200,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Web UI",
            "port": 8582,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "bonds": [
                {
                    "ip_address": "192.168.1.155",
                    "token": "6ec2a88a5bda1547"
                }
            ],
            "include_dimmer": false,
            "include_toggle_state": true,
            "fan_speed_values": false,
            "_bridge": {
                "name": "Bond Bridge 494-00-494",
                "username": "0E:2B:D3:1C:B6:CD",
                "port": 47611
            },
            "platform": "Bond"
        },
        {
            "webhook_port": "51828",
            "cache_directory": "/Users/ravigupta/.homebridge/http-webhooks",
            "sensors": [
                {
                    "id": "Hb",
                    "name": "Hb",
                    "type": "humidity"
                },
                {
                    "id": "Tb",
                    "name": "Tb",
                    "type": "temperature"
                },
                {
                    "id": "FLb",
                    "name": "FLb",
                    "type": "temperature"
                },
                {
                    "id": "FLp",
                    "name": "FLp",
                    "type": "temperature"
                },
                {
                    "id": "FLo",
                    "name": "FLo",
                    "type": "temperature"
                },
                {
                    "id": "FLof",
                    "name": "FLof",
                    "type": "temperature"
                },
                {
                    "id": "VarWb",
                    "name": "VarWb",
                    "type": "light"
                },
                {
                    "id": "VarWbHHmm",
                    "name": "VarWbHHmm",
                    "type": "light"
                },
                {
                    "id": "VarWo",
                    "name": "VarWo",
                    "type": "light"
                },
                {
                    "id": "VarWoHHmm",
                    "name": "VarWoHHmm",
                    "type": "light"
                },
                {
                    "id": "Internet",
                    "name": "Internet",
                    "type": "contact"
                },
                {
                    "id": "Tyxu",
                    "name": "Airport",
                    "type": "temperature"
                },
                {
                    "id": "FLyxu",
                    "name": "Airport FL",
                    "type": "temperature"
                },
                {
                    "id": "Hyxu",
                    "name": "Airport ",
                    "type": "humidity"
                }
            ],
            "statelessswitches": [
                {
                    "id": "test",
                    "name": "Test Stateless Switch",
                    "buttons": [
                        {
                            "name": "Test Button",
                            "double_press": true,
                            "long_press": true
                        }
                    ]
                }
            ],
            "_bridge": {
                "name": "Webhooks 494-00-494",
                "username": "0E:EC:08:6A:FD:22",
                "port": 38624
            },
            "platform": "HttpWebHooks"
        },
        {
            "name": "Tessie",
            "accessToken": “***",
            "prefixName": true,
            "platform": "Tessie",
            "_bridge": {
                "username": "0E:77:B2:52:C5:65",
                "port": 36755
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-yamaha-avr",
        "homebridge-weather-plus",
        "homebridge-rpi",
        "homebridge-meross",
        "homebridge-camera-ffmpeg",
        "@milo526/homebridge-tuya-web",
        "homebridge-smart-irrigation",
        "homebridge-messenger",
        "homebridge-schedule",
        "@kellojo/homebridge-http-webhooks",
        "homebridge-programmable-http-switch",
        "homebridge-http-iot",
        "homebridge-camera-ui",
        "homebridge-eufy-security",
        "homebridge-tesla",
        "homebridge-tplink-smarthome",
        "homebridge-tcc"
    ]
}

**Comment by TeslaOwnerTips** [comment]
I downloaded logs but the entire log file is as shown in the image. If you would like me too attach a log let me know. I have to go to a desktop computer. 
![IMG_8510](https://github.com/Teslemetry/homebridge/assets/78335749/a56d5587-77f3-49e4-92fc-835ba95896df)

**Comment by TeslaOwnerTips** [comment]
![IMG_8511](https://github.com/Teslemetry/homebridge/assets/78335749/8f6866af-6ad0-4189-964a-35b4f3de07a1)

**Comment by Bre77** [comment]
This should be greatly improved now, I would have only expected that level of logging with debug mode on so thats curious.

**Comment by TeslaOwnerTips** [comment]
Latest update infinite child bridge restart loop. 
https://github.com/Teslemetry/homebridge/assets/78335749/a1d33d28-4319-42d0-bffe-2196244ed056

**Comment by Bre77** [comment]
Yes it did. Hotfix is being published now.
