### ISSUE TITLE
Sentry as a lock or security system 

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Teslemetry/homebridge#4]
**Is your feature request related to a problem? Please describe:**

No

**Describe the solution you'd like:**

Have Sentry mode as a Lock or Security System so that it gets grouped with other security accessories. 
![IMG_8509](https://github.com/Teslemetry/homebridge/assets/78335749/e124ab35-014b-4e34-afa2-5b14daaa4556)

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Bre77** [comment]
Security System seems reasonable. I'll make that change.
