### ISSUE TITLE
Vehicle Awake

### ISSUE THREAD

**Issue by TeslaOwnerTips** [Teslemetry/homebridge#5]
Does the vehicle need to be awake before using the accessories?

I tried vent windows and received a no response message. The vehicle was not awake.

**Comment by Bre77** [comment]
The integration is meant to wake-up the vehicle before every command. If this is not working I'll investigate.

**Comment by TeslaOwnerTips** [comment]
Okay   
Before you spend any time on this let me be sure.

**Comment by TeslaOwnerTips** [comment]
On the topic of awake. 

Turning off awake does not appear to put the vehicle to sleep. After a few seconds the accessory turns back on. 

Since the Awake accessory is not needed maybe change it to a contact sensor?

**Comment by Bre77** [comment]
> Turning off awake does not appear to put the vehicle to sleep. After a few seconds the accessory turns back on. 

Correct, you cannot instruct a Tesla vehicle to sleep.

My original brief was to copy the Tesla homebridge integration, which has a wake switch, so that's why it's here. I personally agree it's not very useful.
