### ISSUE TITLE
Question: Does this plugin work with energy products?

### ISSUE THREAD

**Issue by rakgupta** [Teslemetry/homebridge#7]
Hi:

The only examples and discussion I can see is for vehicles. Teslemetry supports energy products (powerwalls and solar), so I wanted to check if the Homebridge plugin also supported those.

Thanks

**Comment by Bre77** [comment]
It will, but currently doesnt. To help me with this, can you describe the kind of things you would want to do with your energy products in Homekit?

**Comment by rakgupta** [comment]
> It will, but currently doesnt. To help me with this, can you describe the kind of things you would want to do with your energy products in Homekit?

I currently connect to my Powerwall via the local API and I want to have a backup process in place in case that stops working. Also, there are certain attributes (e.g. stormwatch status etc.) that are not available via local API. I'm particularly interested in setting up alerts when stormwatch kicks in and goes off as I can then shut off major power consuming devices (HVAC, oven etc.).

I'm reluctant to set up an instance of Home Assistant as I already have multiple automation products (Hubitat, Node-RED, Homebridge, Apple Home)! BTW - I did install the Homebridge plug in but then got stuck as I couldn't see any next steps ☹️

**Comment by rakgupta** [comment]
Attached are examples of the data that I'm gathering from my Powerwall.... hope this gives some idea of what I'm using it for.  Let me know if you have any questions.. Thanks again.

<img width="1278" alt="Screenshot 2024-06-25 at 6 47 09 PM" src="https://github.com/Teslemetry/homebridge/assets/59174606/f9018a3f-7e2b-4663-b1be-5fa9a01f55f5">
<img width="1270" alt="Screenshot 2024-06-25 at 6 46 56 PM" src="https://github.com/Teslemetry/homebridge/assets/59174606/9fbf2287-25a4-4e51-b964-208353451aca">
<img width="1273" alt="Screenshot 2024-06-25 at 6 46 43 PM" src="https://github.com/Teslemetry/homebridge/assets/59174606/b9972297-e97e-40ca-a93b-edc028d24ac3">

**Comment by Bre77** [comment]
I have added some basic switches in the latest release such as battery export, and storm watch participation.

**Comment by rakgupta** [comment]
Thanks - I have to upgrade my instance of HB before I can use the plug-in.
